name: Racket

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ 'BC', 'CS' ]
        version: [ '7.7', '7.8', '7.9', '8.0' ]
    steps:
    - uses: actions/checkout@master
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.1
      with:
        architecture: 'x64' # (x64 or x86), ignored on Linux
        variant: ${{ matrix.variant }}
        version: ${{ matrix.version }}
    - run: raco pkg install --auto
    - run: make test
