name: Racket

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '7.7', '7.8', 'current' ]
    steps:
    - uses: actions/checkout@master
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v0.8
      with:
        architecture: 'x64'   # (x64 or x86), ignored on Linux
        version: ${{ matrix.racket-version }}        # or 'current' for the latest snapshot
    - run: raco pkg install --auto
    - run: raco test .
