name: Test

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  # allow you to run this workflow manually from tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ 'BC', 'CS' ]
        version: [ '7.9', '8.0', '8.1' ]
    steps:
    - uses: actions/checkout@master
    - name: Cache installed packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.racket
        key: ${{ runner.os }}-primes
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.3.1
      with:
        architecture: 'x64' # (x64 or x86), ignored on Linux
        variant: ${{ matrix.variant }}
        version: ${{ matrix.version }}
    - run: raco pkg install --auto
    - run: make ci-test
